## APP CONFIG
application:
  title: Registration API (DEV) =>

## SPRING CONFIG
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

## ACTUATOR CONFIG
management:
  endpoints:
    web:
      exposure:
        include: '*'

## SPRING DOCS CONFIG
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    doc-expansion: false
  packages-to-scan: pl.sda.registrationapi.controller